the VBO meshrenderer seems to require a call to BoInfo::boInfo() by any reason. i have no idea why, as thats basically a noop, but if we dont do that call, we get an undefined reference to BoInfo::boInfo() (which is used by the VBO renderer) on plugin loading.
vertexarrays meshrenderer is not affected by this problem.